# Generated by Django 5.0 on 2023-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
